stateDiagram-v2
    [*] --> CATCHINGBLOCKS
    IDLE --> CATCHINGBLOCKS: CATCHUPBLOCKS
    IDLE --> RUNNING: RUN
    RUNNING --> CATCHINGBLOCKS: CATCHUPBLOCKS
    CATCHINGBLOCKS --> RUNNING: RUN
    RUNNING --> IDLE: STOP
    CATCHINGBLOCKS --> IDLE: STOP
