package utxoseed_test

import (
	"encoding/hex"
	"testing"

	"github.com/bsv-blockchain/go-bt/v2/chainhash"
	"github.com/bsv-blockchain/teranode/pkg/muhash"
	"github.com/bsv-blockchain/teranode/pkg/utxoseed"
	"github.com/stretchr/testify/require"
)

// fixedSet is a small, fixed multiset of UTXOs used for the regression vector.
func buildFixedSetDigest(t *testing.T) [32]byte {
	t.Helper()

	txidA, err := chainhash.NewHashFromStr("00000000000000000000000000000000000000000000000000000000000000aa")
	require.NoError(t, err)
	txidB, err := chainhash.NewHashFromStr("00000000000000000000000000000000000000000000000000000000000000bb")
	require.NoError(t, err)

	m := muhash.New()
	m.Add(utxoseed.Element(*txidA, 0, 100, true, 5000000000, []byte{0x51}))
	m.Add(utxoseed.Element(*txidB, 0, 101, false, 1000, []byte{0x76, 0xa9}))
	m.Add(utxoseed.Element(*txidB, 1, 101, false, 2000, []byte{0x6a}))

	return m.Digest()
}

func TestSetCommitmentOrderIndependent(t *testing.T) {
	txidA, _ := chainhash.NewHashFromStr("00000000000000000000000000000000000000000000000000000000000000aa")
	txidB, _ := chainhash.NewHashFromStr("00000000000000000000000000000000000000000000000000000000000000bb")

	forward := muhash.New()
	forward.Add(utxoseed.Element(*txidA, 0, 100, true, 5000000000, []byte{0x51}))
	forward.Add(utxoseed.Element(*txidB, 0, 101, false, 1000, []byte{0x76, 0xa9}))

	reverse := muhash.New()
	reverse.Add(utxoseed.Element(*txidB, 0, 101, false, 1000, []byte{0x76, 0xa9}))
	reverse.Add(utxoseed.Element(*txidA, 0, 100, true, 5000000000, []byte{0x51}))

	require.Equal(t, forward.Digest(), reverse.Digest())
}

// regressionVector is generated by the implementation and pinned to catch
// accidental changes to the frozen construction.
const regressionVector = "ac0d194b907732f540076012cac33c41acba81f03873bf249f5e03258ca2e9bc"

func TestSetCommitmentRegression(t *testing.T) {
	digest := buildFixedSetDigest(t)
	got := hex.EncodeToString(digest[:])
	require.Equal(t, regressionVector, got,
		"commitment construction changed; if this change is INTENTIONAL, update regressionVector")
}
