// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: services/legacy/peer_api/peer_api.proto

package peer_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CatchupProgress_Phase int32

const (
	CatchupProgress_DOWNLOADING_HEADERS CatchupProgress_Phase = 0
	CatchupProgress_DOWNLOADING_BLOCKS  CatchupProgress_Phase = 1
	CatchupProgress_COMPLETE            CatchupProgress_Phase = 2
	CatchupProgress_FAILED              CatchupProgress_Phase = 3
)

// Enum value maps for CatchupProgress_Phase.
var (
	CatchupProgress_Phase_name = map[int32]string{
		0: "DOWNLOADING_HEADERS",
		1: "DOWNLOADING_BLOCKS",
		2: "COMPLETE",
		3: "FAILED",
	}
	CatchupProgress_Phase_value = map[string]int32{
		"DOWNLOADING_HEADERS": 0,
		"DOWNLOADING_BLOCKS":  1,
		"COMPLETE":            2,
		"FAILED":              3,
	}
)

func (x CatchupProgress_Phase) Enum() *CatchupProgress_Phase {
	p := new(CatchupProgress_Phase)
	*p = x
	return p
}

func (x CatchupProgress_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CatchupProgress_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_services_legacy_peer_api_peer_api_proto_enumTypes[0].Descriptor()
}

func (CatchupProgress_Phase) Type() protoreflect.EnumType {
	return &file_services_legacy_peer_api_peer_api_proto_enumTypes[0]
}

func (x CatchupProgress_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CatchupProgress_Phase.Descriptor instead.
func (CatchupProgress_Phase) EnumDescriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{17, 0}
}

type StreamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamType    uint32                 `protobuf:"varint,1,opt,name=stream_type,json=streamType,proto3" json:"stream_type,omitempty"`
	BytesSent     uint64                 `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesRecv     uint64                 `protobuf:"varint,3,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{0}
}

func (x *StreamInfo) GetStreamType() uint32 {
	if x != nil {
		return x.StreamType
	}
	return 0
}

func (x *StreamInfo) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *StreamInfo) GetBytesRecv() uint64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

type Peer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr             string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	AddrLocal        string                 `protobuf:"bytes,3,opt,name=addrLocal,proto3" json:"addrLocal,omitempty"`
	Services         string                 `protobuf:"bytes,4,opt,name=services,proto3" json:"services,omitempty"`
	LastSend         int64                  `protobuf:"varint,5,opt,name=lastSend,proto3" json:"lastSend,omitempty"`
	LastRecv         int64                  `protobuf:"varint,6,opt,name=lastRecv,proto3" json:"lastRecv,omitempty"`
	SendSize         int64                  `protobuf:"varint,7,opt,name=sendSize,proto3" json:"sendSize,omitempty"`
	RecvSize         int64                  `protobuf:"varint,8,opt,name=recvSize,proto3" json:"recvSize,omitempty"`
	SendMemory       int64                  `protobuf:"varint,9,opt,name=sendMemory,proto3" json:"sendMemory,omitempty"`
	PauseSend        bool                   `protobuf:"varint,10,opt,name=pauseSend,proto3" json:"pauseSend,omitempty"`
	UnpauseSend      bool                   `protobuf:"varint,11,opt,name=unpauseSend,proto3" json:"unpauseSend,omitempty"`
	BytesSent        uint64                 `protobuf:"varint,12,opt,name=bytesSent,proto3" json:"bytesSent,omitempty"`
	BytesReceived    uint64                 `protobuf:"varint,13,opt,name=bytesReceived,proto3" json:"bytesReceived,omitempty"`
	AvgRecvBandwidth int64                  `protobuf:"varint,14,opt,name=avgRecvBandwidth,proto3" json:"avgRecvBandwidth,omitempty"`
	AssocId          string                 `protobuf:"bytes,15,opt,name=assocId,proto3" json:"assocId,omitempty"`
	StreamPolicy     string                 `protobuf:"bytes,16,opt,name=streamPolicy,proto3" json:"streamPolicy,omitempty"`
	Inbound          bool                   `protobuf:"varint,17,opt,name=inbound,proto3" json:"inbound,omitempty"`
	ConnTime         int64                  `protobuf:"varint,18,opt,name=connTime,proto3" json:"connTime,omitempty"`
	PingTime         int64                  `protobuf:"varint,19,opt,name=pingTime,proto3" json:"pingTime,omitempty"`
	TimeOffset       int64                  `protobuf:"varint,20,opt,name=timeOffset,proto3" json:"timeOffset,omitempty"`
	Version          uint32                 `protobuf:"varint,21,opt,name=version,proto3" json:"version,omitempty"`
	SubVer           string                 `protobuf:"bytes,22,opt,name=subVer,proto3" json:"subVer,omitempty"`
	StartingHeight   int32                  `protobuf:"varint,23,opt,name=startingHeight,proto3" json:"startingHeight,omitempty"`
	CurrentHeight    int32                  `protobuf:"varint,24,opt,name=currentHeight,proto3" json:"currentHeight,omitempty"`
	Banscore         int32                  `protobuf:"varint,25,opt,name=banscore,proto3" json:"banscore,omitempty"`
	Whitelisted      bool                   `protobuf:"varint,26,opt,name=whitelisted,proto3" json:"whitelisted,omitempty"`
	FeeFilter        int64                  `protobuf:"varint,27,opt,name=feeFilter,proto3" json:"feeFilter,omitempty"`
	Streams          []*StreamInfo          `protobuf:"bytes,28,rep,name=streams,proto3" json:"streams,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{1}
}

func (x *Peer) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Peer) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Peer) GetAddrLocal() string {
	if x != nil {
		return x.AddrLocal
	}
	return ""
}

func (x *Peer) GetServices() string {
	if x != nil {
		return x.Services
	}
	return ""
}

func (x *Peer) GetLastSend() int64 {
	if x != nil {
		return x.LastSend
	}
	return 0
}

func (x *Peer) GetLastRecv() int64 {
	if x != nil {
		return x.LastRecv
	}
	return 0
}

func (x *Peer) GetSendSize() int64 {
	if x != nil {
		return x.SendSize
	}
	return 0
}

func (x *Peer) GetRecvSize() int64 {
	if x != nil {
		return x.RecvSize
	}
	return 0
}

func (x *Peer) GetSendMemory() int64 {
	if x != nil {
		return x.SendMemory
	}
	return 0
}

func (x *Peer) GetPauseSend() bool {
	if x != nil {
		return x.PauseSend
	}
	return false
}

func (x *Peer) GetUnpauseSend() bool {
	if x != nil {
		return x.UnpauseSend
	}
	return false
}

func (x *Peer) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *Peer) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *Peer) GetAvgRecvBandwidth() int64 {
	if x != nil {
		return x.AvgRecvBandwidth
	}
	return 0
}

func (x *Peer) GetAssocId() string {
	if x != nil {
		return x.AssocId
	}
	return ""
}

func (x *Peer) GetStreamPolicy() string {
	if x != nil {
		return x.StreamPolicy
	}
	return ""
}

func (x *Peer) GetInbound() bool {
	if x != nil {
		return x.Inbound
	}
	return false
}

func (x *Peer) GetConnTime() int64 {
	if x != nil {
		return x.ConnTime
	}
	return 0
}

func (x *Peer) GetPingTime() int64 {
	if x != nil {
		return x.PingTime
	}
	return 0
}

func (x *Peer) GetTimeOffset() int64 {
	if x != nil {
		return x.TimeOffset
	}
	return 0
}

func (x *Peer) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Peer) GetSubVer() string {
	if x != nil {
		return x.SubVer
	}
	return ""
}

func (x *Peer) GetStartingHeight() int32 {
	if x != nil {
		return x.StartingHeight
	}
	return 0
}

func (x *Peer) GetCurrentHeight() int32 {
	if x != nil {
		return x.CurrentHeight
	}
	return 0
}

func (x *Peer) GetBanscore() int32 {
	if x != nil {
		return x.Banscore
	}
	return 0
}

func (x *Peer) GetWhitelisted() bool {
	if x != nil {
		return x.Whitelisted
	}
	return false
}

func (x *Peer) GetFeeFilter() int64 {
	if x != nil {
		return x.FeeFilter
	}
	return 0
}

func (x *Peer) GetStreams() []*StreamInfo {
	if x != nil {
		return x.Streams
	}
	return nil
}

type GetPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersResponse) Reset() {
	*x = GetPeersResponse{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersResponse) ProtoMessage() {}

func (x *GetPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersResponse.ProtoReflect.Descriptor instead.
func (*GetPeersResponse) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetPeersResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type GetPeerCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerCountResponse) Reset() {
	*x = GetPeerCountResponse{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerCountResponse) ProtoMessage() {}

func (x *GetPeerCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerCountResponse.ProtoReflect.Descriptor instead.
func (*GetPeerCountResponse) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetPeerCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BanPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Until         int64                  `protobuf:"varint,2,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanPeerRequest) Reset() {
	*x = BanPeerRequest{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPeerRequest) ProtoMessage() {}

func (x *BanPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPeerRequest.ProtoReflect.Descriptor instead.
func (*BanPeerRequest) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{4}
}

func (x *BanPeerRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *BanPeerRequest) GetUntil() int64 {
	if x != nil {
		return x.Until
	}
	return 0
}

type BanPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanPeerResponse) Reset() {
	*x = BanPeerResponse{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPeerResponse) ProtoMessage() {}

func (x *BanPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPeerResponse.ProtoReflect.Descriptor instead.
func (*BanPeerResponse) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{5}
}

func (x *BanPeerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type UnbanPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanPeerRequest) Reset() {
	*x = UnbanPeerRequest{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanPeerRequest) ProtoMessage() {}

func (x *UnbanPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanPeerRequest.ProtoReflect.Descriptor instead.
func (*UnbanPeerRequest) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{6}
}

func (x *UnbanPeerRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type UnbanPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanPeerResponse) Reset() {
	*x = UnbanPeerResponse{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanPeerResponse) ProtoMessage() {}

func (x *UnbanPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanPeerResponse.ProtoReflect.Descriptor instead.
func (*UnbanPeerResponse) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{7}
}

func (x *UnbanPeerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type IsBannedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpOrSubnet    string                 `protobuf:"bytes,1,opt,name=ipOrSubnet,proto3" json:"ipOrSubnet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsBannedRequest) Reset() {
	*x = IsBannedRequest{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsBannedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsBannedRequest) ProtoMessage() {}

func (x *IsBannedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsBannedRequest.ProtoReflect.Descriptor instead.
func (*IsBannedRequest) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{8}
}

func (x *IsBannedRequest) GetIpOrSubnet() string {
	if x != nil {
		return x.IpOrSubnet
	}
	return ""
}

type IsBannedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsBanned      bool                   `protobuf:"varint,1,opt,name=isBanned,proto3" json:"isBanned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsBannedResponse) Reset() {
	*x = IsBannedResponse{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsBannedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsBannedResponse) ProtoMessage() {}

func (x *IsBannedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsBannedResponse.ProtoReflect.Descriptor instead.
func (*IsBannedResponse) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{9}
}

func (x *IsBannedResponse) GetIsBanned() bool {
	if x != nil {
		return x.IsBanned
	}
	return false
}

type ListBannedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banned        []string               `protobuf:"bytes,1,rep,name=banned,proto3" json:"banned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBannedResponse) Reset() {
	*x = ListBannedResponse{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBannedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBannedResponse) ProtoMessage() {}

func (x *ListBannedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBannedResponse.ProtoReflect.Descriptor instead.
func (*ListBannedResponse) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{10}
}

func (x *ListBannedResponse) GetBanned() []string {
	if x != nil {
		return x.Banned
	}
	return nil
}

type ClearBannedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearBannedResponse) Reset() {
	*x = ClearBannedResponse{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearBannedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearBannedResponse) ProtoMessage() {}

func (x *ClearBannedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearBannedResponse.ProtoReflect.Descriptor instead.
func (*ClearBannedResponse) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{11}
}

func (x *ClearBannedResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// FetchHeadersFromPeerRequest requests block headers from a specific peer
// using the Bitcoin wire protocol getheaders message.
type FetchHeadersFromPeerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// peer_addr is the "host:port" address of the connected legacy peer.
	PeerAddr string `protobuf:"bytes,1,opt,name=peer_addr,json=peerAddr,proto3" json:"peer_addr,omitempty"`
	// locator_hashes is the block locator (each entry is a 32-byte LE hash).
	LocatorHashes [][]byte `protobuf:"bytes,2,rep,name=locator_hashes,json=locatorHashes,proto3" json:"locator_hashes,omitempty"`
	// stop_hash is the hash where the peer should stop (32-byte LE).
	// All-zeros means return up to the chain tip.
	StopHash      []byte `protobuf:"bytes,3,opt,name=stop_hash,json=stopHash,proto3" json:"stop_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchHeadersFromPeerRequest) Reset() {
	*x = FetchHeadersFromPeerRequest{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchHeadersFromPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchHeadersFromPeerRequest) ProtoMessage() {}

func (x *FetchHeadersFromPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchHeadersFromPeerRequest.ProtoReflect.Descriptor instead.
func (*FetchHeadersFromPeerRequest) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{12}
}

func (x *FetchHeadersFromPeerRequest) GetPeerAddr() string {
	if x != nil {
		return x.PeerAddr
	}
	return ""
}

func (x *FetchHeadersFromPeerRequest) GetLocatorHashes() [][]byte {
	if x != nil {
		return x.LocatorHashes
	}
	return nil
}

func (x *FetchHeadersFromPeerRequest) GetStopHash() []byte {
	if x != nil {
		return x.StopHash
	}
	return nil
}

// FetchHeadersFromPeerResponse returns the raw concatenated 80-byte block headers
// received from the peer.
type FetchHeadersFromPeerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// header_bytes is a sequence of concatenated 80-byte block headers.
	HeaderBytes   []byte `protobuf:"bytes,1,opt,name=header_bytes,json=headerBytes,proto3" json:"header_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchHeadersFromPeerResponse) Reset() {
	*x = FetchHeadersFromPeerResponse{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchHeadersFromPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchHeadersFromPeerResponse) ProtoMessage() {}

func (x *FetchHeadersFromPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchHeadersFromPeerResponse.ProtoReflect.Descriptor instead.
func (*FetchHeadersFromPeerResponse) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{13}
}

func (x *FetchHeadersFromPeerResponse) GetHeaderBytes() []byte {
	if x != nil {
		return x.HeaderBytes
	}
	return nil
}

// FetchBlockFromPeerRequest requests a specific block from a peer via getdata.
type FetchBlockFromPeerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// peer_addr is the "host:port" address of the connected legacy peer.
	PeerAddr string `protobuf:"bytes,1,opt,name=peer_addr,json=peerAddr,proto3" json:"peer_addr,omitempty"`
	// block_hash is the 32-byte LE hash of the block to fetch.
	BlockHash     []byte `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchBlockFromPeerRequest) Reset() {
	*x = FetchBlockFromPeerRequest{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchBlockFromPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBlockFromPeerRequest) ProtoMessage() {}

func (x *FetchBlockFromPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBlockFromPeerRequest.ProtoReflect.Descriptor instead.
func (*FetchBlockFromPeerRequest) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{14}
}

func (x *FetchBlockFromPeerRequest) GetPeerAddr() string {
	if x != nil {
		return x.PeerAddr
	}
	return ""
}

func (x *FetchBlockFromPeerRequest) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

// FetchBlockFromPeerResponse returns the raw serialized block bytes.
type FetchBlockFromPeerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// block_bytes is the full serialized Bitcoin block.
	BlockBytes    []byte `protobuf:"bytes,1,opt,name=block_bytes,json=blockBytes,proto3" json:"block_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchBlockFromPeerResponse) Reset() {
	*x = FetchBlockFromPeerResponse{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchBlockFromPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBlockFromPeerResponse) ProtoMessage() {}

func (x *FetchBlockFromPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBlockFromPeerResponse.ProtoReflect.Descriptor instead.
func (*FetchBlockFromPeerResponse) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{15}
}

func (x *FetchBlockFromPeerResponse) GetBlockBytes() []byte {
	if x != nil {
		return x.BlockBytes
	}
	return nil
}

// DelegateCatchupRequest asks the legacy service to sync from a specific
// wire-protocol peer up to a target height. BlockValidation uses this to
// delegate wire-protocol catchup to legacy while retaining peer selection
// and retry decisions.
type DelegateCatchupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// peer_addr is the "host:port" of the already-connected wire peer.
	PeerAddr string `protobuf:"bytes,1,opt,name=peer_addr,json=peerAddr,proto3" json:"peer_addr,omitempty"`
	// target_height is the block height to sync up to.
	TargetHeight  uint32 `protobuf:"varint,2,opt,name=target_height,json=targetHeight,proto3" json:"target_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegateCatchupRequest) Reset() {
	*x = DelegateCatchupRequest{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateCatchupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateCatchupRequest) ProtoMessage() {}

func (x *DelegateCatchupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateCatchupRequest.ProtoReflect.Descriptor instead.
func (*DelegateCatchupRequest) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{16}
}

func (x *DelegateCatchupRequest) GetPeerAddr() string {
	if x != nil {
		return x.PeerAddr
	}
	return ""
}

func (x *DelegateCatchupRequest) GetTargetHeight() uint32 {
	if x != nil {
		return x.TargetHeight
	}
	return 0
}

// CatchupProgress is streamed back to the caller during a delegated catchup.
type CatchupProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// phase indicates the current stage of the catchup operation.
	Phase CatchupProgress_Phase `protobuf:"varint,1,opt,name=phase,proto3,enum=peer_api.CatchupProgress_Phase" json:"phase,omitempty"`
	// current_height is the height of the last successfully processed block.
	CurrentHeight uint32 `protobuf:"varint,2,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`
	// target_height is the height we are syncing to.
	TargetHeight uint32 `protobuf:"varint,3,opt,name=target_height,json=targetHeight,proto3" json:"target_height,omitempty"`
	// blocks_remaining is how many blocks are left to process.
	BlocksRemaining int32 `protobuf:"varint,4,opt,name=blocks_remaining,json=blocksRemaining,proto3" json:"blocks_remaining,omitempty"`
	// error_message is non-empty only when phase == FAILED.
	ErrorMessage string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// error_category classifies the failure: "network", "validation", "pruned", "peer_misbehavior".
	ErrorCategory string `protobuf:"bytes,6,opt,name=error_category,json=errorCategory,proto3" json:"error_category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatchupProgress) Reset() {
	*x = CatchupProgress{}
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchupProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchupProgress) ProtoMessage() {}

func (x *CatchupProgress) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchupProgress.ProtoReflect.Descriptor instead.
func (*CatchupProgress) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{17}
}

func (x *CatchupProgress) GetPhase() CatchupProgress_Phase {
	if x != nil {
		return x.Phase
	}
	return CatchupProgress_DOWNLOADING_HEADERS
}

func (x *CatchupProgress) GetCurrentHeight() uint32 {
	if x != nil {
		return x.CurrentHeight
	}
	return 0
}

func (x *CatchupProgress) GetTargetHeight() uint32 {
	if x != nil {
		return x.TargetHeight
	}
	return 0
}

func (x *CatchupProgress) GetBlocksRemaining() int32 {
	if x != nil {
		return x.BlocksRemaining
	}
	return 0
}

func (x *CatchupProgress) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CatchupProgress) GetErrorCategory() string {
	if x != nil {
		return x.ErrorCategory
	}
	return ""
}

var File_services_legacy_peer_api_peer_api_proto protoreflect.FileDescriptor

const file_services_legacy_peer_api_peer_api_proto_rawDesc = "" +
	"\n" +
	"'services/legacy/peer_api/peer_api.proto\x12\bpeer_api\x1a\x1bgoogle/protobuf/empty.proto\"k\n" +
	"\n" +
	"StreamInfo\x12\x1f\n" +
	"\vstream_type\x18\x01 \x01(\rR\n" +
	"streamType\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x04R\tbytesSent\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\x03 \x01(\x04R\tbytesRecv\"\xe0\x06\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1c\n" +
	"\taddrLocal\x18\x03 \x01(\tR\taddrLocal\x12\x1a\n" +
	"\bservices\x18\x04 \x01(\tR\bservices\x12\x1a\n" +
	"\blastSend\x18\x05 \x01(\x03R\blastSend\x12\x1a\n" +
	"\blastRecv\x18\x06 \x01(\x03R\blastRecv\x12\x1a\n" +
	"\bsendSize\x18\a \x01(\x03R\bsendSize\x12\x1a\n" +
	"\brecvSize\x18\b \x01(\x03R\brecvSize\x12\x1e\n" +
	"\n" +
	"sendMemory\x18\t \x01(\x03R\n" +
	"sendMemory\x12\x1c\n" +
	"\tpauseSend\x18\n" +
	" \x01(\bR\tpauseSend\x12 \n" +
	"\vunpauseSend\x18\v \x01(\bR\vunpauseSend\x12\x1c\n" +
	"\tbytesSent\x18\f \x01(\x04R\tbytesSent\x12$\n" +
	"\rbytesReceived\x18\r \x01(\x04R\rbytesReceived\x12*\n" +
	"\x10avgRecvBandwidth\x18\x0e \x01(\x03R\x10avgRecvBandwidth\x12\x18\n" +
	"\aassocId\x18\x0f \x01(\tR\aassocId\x12\"\n" +
	"\fstreamPolicy\x18\x10 \x01(\tR\fstreamPolicy\x12\x18\n" +
	"\ainbound\x18\x11 \x01(\bR\ainbound\x12\x1a\n" +
	"\bconnTime\x18\x12 \x01(\x03R\bconnTime\x12\x1a\n" +
	"\bpingTime\x18\x13 \x01(\x03R\bpingTime\x12\x1e\n" +
	"\n" +
	"timeOffset\x18\x14 \x01(\x03R\n" +
	"timeOffset\x12\x18\n" +
	"\aversion\x18\x15 \x01(\rR\aversion\x12\x16\n" +
	"\x06subVer\x18\x16 \x01(\tR\x06subVer\x12&\n" +
	"\x0estartingHeight\x18\x17 \x01(\x05R\x0estartingHeight\x12$\n" +
	"\rcurrentHeight\x18\x18 \x01(\x05R\rcurrentHeight\x12\x1a\n" +
	"\bbanscore\x18\x19 \x01(\x05R\bbanscore\x12 \n" +
	"\vwhitelisted\x18\x1a \x01(\bR\vwhitelisted\x12\x1c\n" +
	"\tfeeFilter\x18\x1b \x01(\x03R\tfeeFilter\x12.\n" +
	"\astreams\x18\x1c \x03(\v2\x14.peer_api.StreamInfoR\astreams\"8\n" +
	"\x10GetPeersResponse\x12$\n" +
	"\x05peers\x18\x01 \x03(\v2\x0e.peer_api.PeerR\x05peers\",\n" +
	"\x14GetPeerCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\":\n" +
	"\x0eBanPeerRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x14\n" +
	"\x05until\x18\x02 \x01(\x03R\x05until\"!\n" +
	"\x0fBanPeerResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"&\n" +
	"\x10UnbanPeerRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"#\n" +
	"\x11UnbanPeerResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"1\n" +
	"\x0fIsBannedRequest\x12\x1e\n" +
	"\n" +
	"ipOrSubnet\x18\x01 \x01(\tR\n" +
	"ipOrSubnet\".\n" +
	"\x10IsBannedResponse\x12\x1a\n" +
	"\bisBanned\x18\x01 \x01(\bR\bisBanned\",\n" +
	"\x12ListBannedResponse\x12\x16\n" +
	"\x06banned\x18\x01 \x03(\tR\x06banned\"%\n" +
	"\x13ClearBannedResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"~\n" +
	"\x1bFetchHeadersFromPeerRequest\x12\x1b\n" +
	"\tpeer_addr\x18\x01 \x01(\tR\bpeerAddr\x12%\n" +
	"\x0elocator_hashes\x18\x02 \x03(\fR\rlocatorHashes\x12\x1b\n" +
	"\tstop_hash\x18\x03 \x01(\fR\bstopHash\"A\n" +
	"\x1cFetchHeadersFromPeerResponse\x12!\n" +
	"\fheader_bytes\x18\x01 \x01(\fR\vheaderBytes\"W\n" +
	"\x19FetchBlockFromPeerRequest\x12\x1b\n" +
	"\tpeer_addr\x18\x01 \x01(\tR\bpeerAddr\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\"=\n" +
	"\x1aFetchBlockFromPeerResponse\x12\x1f\n" +
	"\vblock_bytes\x18\x01 \x01(\fR\n" +
	"blockBytes\"Z\n" +
	"\x16DelegateCatchupRequest\x12\x1b\n" +
	"\tpeer_addr\x18\x01 \x01(\tR\bpeerAddr\x12#\n" +
	"\rtarget_height\x18\x02 \x01(\rR\ftargetHeight\"\xdf\x02\n" +
	"\x0fCatchupProgress\x125\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x1f.peer_api.CatchupProgress.PhaseR\x05phase\x12%\n" +
	"\x0ecurrent_height\x18\x02 \x01(\rR\rcurrentHeight\x12#\n" +
	"\rtarget_height\x18\x03 \x01(\rR\ftargetHeight\x12)\n" +
	"\x10blocks_remaining\x18\x04 \x01(\x05R\x0fblocksRemaining\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0eerror_category\x18\x06 \x01(\tR\rerrorCategory\"R\n" +
	"\x05Phase\x12\x17\n" +
	"\x13DOWNLOADING_HEADERS\x10\x00\x12\x16\n" +
	"\x12DOWNLOADING_BLOCKS\x10\x01\x12\f\n" +
	"\bCOMPLETE\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032\x96\x06\n" +
	"\vPeerService\x12@\n" +
	"\bGetPeers\x12\x16.google.protobuf.Empty\x1a\x1a.peer_api.GetPeersResponse\"\x00\x12@\n" +
	"\aBanPeer\x12\x18.peer_api.BanPeerRequest\x1a\x19.peer_api.BanPeerResponse\"\x00\x12F\n" +
	"\tUnbanPeer\x12\x1a.peer_api.UnbanPeerRequest\x1a\x1b.peer_api.UnbanPeerResponse\"\x00\x12C\n" +
	"\bIsBanned\x12\x19.peer_api.IsBannedRequest\x1a\x1a.peer_api.IsBannedResponse\"\x00\x12D\n" +
	"\n" +
	"ListBanned\x12\x16.google.protobuf.Empty\x1a\x1c.peer_api.ListBannedResponse\"\x00\x12F\n" +
	"\vClearBanned\x12\x16.google.protobuf.Empty\x1a\x1d.peer_api.ClearBannedResponse\"\x00\x12H\n" +
	"\fGetPeerCount\x12\x16.google.protobuf.Empty\x1a\x1e.peer_api.GetPeerCountResponse\"\x00\x12g\n" +
	"\x14FetchHeadersFromPeer\x12%.peer_api.FetchHeadersFromPeerRequest\x1a&.peer_api.FetchHeadersFromPeerResponse\"\x00\x12a\n" +
	"\x12FetchBlockFromPeer\x12#.peer_api.FetchBlockFromPeerRequest\x1a$.peer_api.FetchBlockFromPeerResponse\"\x00\x12R\n" +
	"\x0fDelegateCatchup\x12 .peer_api.DelegateCatchupRequest\x1a\x19.peer_api.CatchupProgress\"\x000\x01B\rZ\v./;peer_apib\x06proto3"

var (
	file_services_legacy_peer_api_peer_api_proto_rawDescOnce sync.Once
	file_services_legacy_peer_api_peer_api_proto_rawDescData []byte
)

func file_services_legacy_peer_api_peer_api_proto_rawDescGZIP() []byte {
	file_services_legacy_peer_api_peer_api_proto_rawDescOnce.Do(func() {
		file_services_legacy_peer_api_peer_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_legacy_peer_api_peer_api_proto_rawDesc), len(file_services_legacy_peer_api_peer_api_proto_rawDesc)))
	})
	return file_services_legacy_peer_api_peer_api_proto_rawDescData
}

var file_services_legacy_peer_api_peer_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_legacy_peer_api_peer_api_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_services_legacy_peer_api_peer_api_proto_goTypes = []any{
	(CatchupProgress_Phase)(0),           // 0: peer_api.CatchupProgress.Phase
	(*StreamInfo)(nil),                   // 1: peer_api.StreamInfo
	(*Peer)(nil),                         // 2: peer_api.Peer
	(*GetPeersResponse)(nil),             // 3: peer_api.GetPeersResponse
	(*GetPeerCountResponse)(nil),         // 4: peer_api.GetPeerCountResponse
	(*BanPeerRequest)(nil),               // 5: peer_api.BanPeerRequest
	(*BanPeerResponse)(nil),              // 6: peer_api.BanPeerResponse
	(*UnbanPeerRequest)(nil),             // 7: peer_api.UnbanPeerRequest
	(*UnbanPeerResponse)(nil),            // 8: peer_api.UnbanPeerResponse
	(*IsBannedRequest)(nil),              // 9: peer_api.IsBannedRequest
	(*IsBannedResponse)(nil),             // 10: peer_api.IsBannedResponse
	(*ListBannedResponse)(nil),           // 11: peer_api.ListBannedResponse
	(*ClearBannedResponse)(nil),          // 12: peer_api.ClearBannedResponse
	(*FetchHeadersFromPeerRequest)(nil),  // 13: peer_api.FetchHeadersFromPeerRequest
	(*FetchHeadersFromPeerResponse)(nil), // 14: peer_api.FetchHeadersFromPeerResponse
	(*FetchBlockFromPeerRequest)(nil),    // 15: peer_api.FetchBlockFromPeerRequest
	(*FetchBlockFromPeerResponse)(nil),   // 16: peer_api.FetchBlockFromPeerResponse
	(*DelegateCatchupRequest)(nil),       // 17: peer_api.DelegateCatchupRequest
	(*CatchupProgress)(nil),              // 18: peer_api.CatchupProgress
	(*emptypb.Empty)(nil),                // 19: google.protobuf.Empty
}
var file_services_legacy_peer_api_peer_api_proto_depIdxs = []int32{
	1,  // 0: peer_api.Peer.streams:type_name -> peer_api.StreamInfo
	2,  // 1: peer_api.GetPeersResponse.peers:type_name -> peer_api.Peer
	0,  // 2: peer_api.CatchupProgress.phase:type_name -> peer_api.CatchupProgress.Phase
	19, // 3: peer_api.PeerService.GetPeers:input_type -> google.protobuf.Empty
	5,  // 4: peer_api.PeerService.BanPeer:input_type -> peer_api.BanPeerRequest
	7,  // 5: peer_api.PeerService.UnbanPeer:input_type -> peer_api.UnbanPeerRequest
	9,  // 6: peer_api.PeerService.IsBanned:input_type -> peer_api.IsBannedRequest
	19, // 7: peer_api.PeerService.ListBanned:input_type -> google.protobuf.Empty
	19, // 8: peer_api.PeerService.ClearBanned:input_type -> google.protobuf.Empty
	19, // 9: peer_api.PeerService.GetPeerCount:input_type -> google.protobuf.Empty
	13, // 10: peer_api.PeerService.FetchHeadersFromPeer:input_type -> peer_api.FetchHeadersFromPeerRequest
	15, // 11: peer_api.PeerService.FetchBlockFromPeer:input_type -> peer_api.FetchBlockFromPeerRequest
	17, // 12: peer_api.PeerService.DelegateCatchup:input_type -> peer_api.DelegateCatchupRequest
	3,  // 13: peer_api.PeerService.GetPeers:output_type -> peer_api.GetPeersResponse
	6,  // 14: peer_api.PeerService.BanPeer:output_type -> peer_api.BanPeerResponse
	8,  // 15: peer_api.PeerService.UnbanPeer:output_type -> peer_api.UnbanPeerResponse
	10, // 16: peer_api.PeerService.IsBanned:output_type -> peer_api.IsBannedResponse
	11, // 17: peer_api.PeerService.ListBanned:output_type -> peer_api.ListBannedResponse
	12, // 18: peer_api.PeerService.ClearBanned:output_type -> peer_api.ClearBannedResponse
	4,  // 19: peer_api.PeerService.GetPeerCount:output_type -> peer_api.GetPeerCountResponse
	14, // 20: peer_api.PeerService.FetchHeadersFromPeer:output_type -> peer_api.FetchHeadersFromPeerResponse
	16, // 21: peer_api.PeerService.FetchBlockFromPeer:output_type -> peer_api.FetchBlockFromPeerResponse
	18, // 22: peer_api.PeerService.DelegateCatchup:output_type -> peer_api.CatchupProgress
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_services_legacy_peer_api_peer_api_proto_init() }
func file_services_legacy_peer_api_peer_api_proto_init() {
	if File_services_legacy_peer_api_peer_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_legacy_peer_api_peer_api_proto_rawDesc), len(file_services_legacy_peer_api_peer_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_legacy_peer_api_peer_api_proto_goTypes,
		DependencyIndexes: file_services_legacy_peer_api_peer_api_proto_depIdxs,
		EnumInfos:         file_services_legacy_peer_api_peer_api_proto_enumTypes,
		MessageInfos:      file_services_legacy_peer_api_peer_api_proto_msgTypes,
	}.Build()
	File_services_legacy_peer_api_peer_api_proto = out.File
	file_services_legacy_peer_api_peer_api_proto_goTypes = nil
	file_services_legacy_peer_api_peer_api_proto_depIdxs = nil
}
