// Package seedpack splits a byte stream into content-defined chunks and binds
// them with a manifest, forming a portable, deduplicated seed package.
package seedpack

import (
	"bufio"
	"bytes"
	"io"
)

// gear is a fixed, deterministic 256-entry table for the gear rolling hash,
// generated by splitmix64 from a constant seed. It is frozen — changing it
// changes chunk boundaries (and therefore cross-snapshot dedup, though not
// correctness, since reassembly follows the manifest, not re-chunking).
var gear = func() [256]uint64 {
	var t [256]uint64
	x := uint64(0x1234567890abcdef)
	for i := range t {
		x += 0x9e3779b97f4a7c15
		z := x
		z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9
		z = (z ^ (z >> 27)) * 0x94d049bb133111eb
		z = z ^ (z >> 31)
		t[i] = z
	}
	return t
}()

// Config bounds chunk sizes and sets the boundary probability via Mask.
// A boundary is cut when (hash & Mask) == 0, giving an average chunk size of
// roughly Mask+1 bytes, clamped to [Min, Max].
type Config struct {
	Min  int
	Max  int
	Mask uint64
}

// DefaultConfig returns production chunking parameters: ~1 MiB average chunks,
// bounded to [256 KiB, 4 MiB].
func DefaultConfig() Config {
	return Config{Min: 256 << 10, Max: 4 << 20, Mask: (1 << 20) - 1}
}

// SplitStream reads r and calls emit once per content-defined chunk, in order.
// Each chunk passed to emit is owned by emit (a fresh slice). It streams with
// bounded memory (at most Max buffered).
func SplitStream(r io.Reader, cfg Config, emit func(chunk []byte) error) error {
	br := bufio.NewReader(r)

	buf := make([]byte, 0, cfg.Max)
	var h uint64

	flush := func() error {
		c := make([]byte, len(buf))
		copy(c, buf)

		if err := emit(c); err != nil {
			return err
		}

		buf = buf[:0]
		h = 0

		return nil
	}

	for {
		b, err := br.ReadByte()
		if err == io.EOF {
			if len(buf) > 0 {
				return flush()
			}

			return nil
		}

		if err != nil {
			return err
		}

		buf = append(buf, b)
		h = (h << 1) + gear[b]

		if len(buf) >= cfg.Max || (len(buf) >= cfg.Min && (h&cfg.Mask) == 0) {
			if err := flush(); err != nil {
				return err
			}
		}
	}
}

// Split is the in-memory convenience form of SplitStream.
func Split(data []byte, cfg Config) [][]byte {
	var chunks [][]byte

	_ = SplitStream(bytes.NewReader(data), cfg, func(c []byte) error {
		chunks = append(chunks, c)
		return nil
	})

	return chunks
}
