package settings

import (
	"net/url"
	"time"
)

// AlertSettings configures the alert notification service.
type AlertSettings struct {
	GenesisKeys              []string      `key:"alert_genesis_keys" desc:"Genesis public keys for alert verification" default:"" category:"Alert" usage:"Keys that can sign alerts" type:"[]string" longdesc:"### Purpose\nDefines the list of genesis public keys authorized to sign alert messages on the BSV Blockchain network. Alert messages signed with these keys are considered authoritative network-wide announcements.\n\n### Use Cases\n- Critical security advisories\n- Protocol upgrade notices\n- Emergency communications\n\n### Format\nKeys in **hexadecimal format**, separated by |.\n\n### How It Works\n- Only messages signed by these keys will be processed and relayed\n- Empty list disables genesis alert verification\n\n### Recommendations\n- Production nodes should include official BSV alert keys for network security notices\n- Test networks may use custom keys for isolated alert testing"`
	P2PPrivateKey            string        `redact:"true" key:"alert_p2p_private_key" desc:"P2P private key for alert service" default:"" category:"Alert" usage:"Identity key for P2P network" type:"string" longdesc:"### Purpose\nProvides the **Ed25519** or **secp256k1** private key for alert service P2P network identity, used to authenticate this node on the alert P2P network and sign outgoing alert messages (if this node is an alert originator).\n\n### Format\nHex-encoded private key.\n\n### Values\n- **Empty** - Auto-generation of ephemeral identity\n- **Set value** - Persistent identity across restarts\n\n### How It Works\nIf this node is authorized to create alerts, the key must match a key in GenesisKeys. Regular nodes use this only for P2P authentication.\n\n### Recommendations\n- Use persistent keys for alert originator nodes\n- Ephemeral keys are acceptable for regular relay nodes"`
	ProtocolID               string        `key:"alert_protocol_id" desc:"Protocol ID for alert P2P network" default:"/bitcoin/alert-system/1.0.0" category:"Alert" usage:"Identifies alert protocol version" type:"string" longdesc:"### Purpose\nSpecifies the **LibP2P protocol identifier** for the Bitcoin alert system P2P network, determining which peers can communicate.\n\n### How It Works\nNodes only communicate with peers supporting the same protocol ID. Version number indicates protocol compatibility - nodes with different versions may not interoperate.\n\n### Values\n- **/bitcoin/alert-system/1.0.0** (default) - Standard BSV alert network\n- Custom values for isolated test networks\n\n### Recommendations\n- Use the default for production nodes on the main BSV network\n- Change only if running an isolated alert network for testing"`
	StoreURL                 *url.URL      `key:"alert_store" desc:"Storage URL for alert data (parsed)" default:"sqlite:///alert" category:"Alert" usage:"Parsed URL for alert storage" type:"url" longdesc:"### Purpose\nProvides the parsed URL form of the alert_store setting for programmatic access to storage configuration components.\n\n### How It Works\nThis is the same value as alert_store but pre-parsed into URL components (scheme, host, path, credentials) for use by the alert service during storage backend initialization.\n\n### Recommendations\n- Configure via **alert_store** setting; this field is derived automatically\n- Use for programmatic access to individual URL components"`
	TopicName                string        `key:"alert_topic_name" desc:"P2P topic name for alerts" default:"bitcoin_alert_system" category:"Alert" usage:"PubSub topic for alert distribution" type:"string" longdesc:"### Purpose\nSpecifies the **LibP2P PubSub topic name** for distributing alert messages across the P2P network.\n\n### How It Works\n- All nodes subscribe to this topic to receive alerts\n- Nodes only see alerts published to topics they subscribe to\n- Topic names are **case-sensitive**\n\n### Values\n- **bitcoin_alert_system** (default) - Standard BSV alert network topic\n- Custom values for isolated test networks\n\n### Recommendations\n- Use the default for production nodes\n- Change only for isolated test networks to avoid cross-contamination"`
	P2PBootstrapPeer         string        `key:"alert_p2p_bootstrap_peer" desc:"Bootstrap peer multiaddr for the alert P2P network" default:"" category:"Alert" usage:"Private alert network bootstrap" type:"string" longdesc:"### Purpose\nAdds one libp2p multiaddr (for example /ip4/10.0.0.5/tcp/9908/p2p/12D3Koo...) to the alert P2P bootstrap list. The alert library always tries the public IPFS bootstrap peers as well; this setting lets an isolated network (regtest, private testnet) bootstrap its DHT without internet access.\n\n### Values\n- **Empty** (default) - Only the public IPFS bootstrap peers are used\n- **Multiaddr** - Also connect to this peer during DHT initialisation\n\n### Recommendations\n- Point it at a go-alert-system node (or another teranode alert service) on private networks\n- Leave empty on mainnet"`
	P2PAllowPrivateIPs       bool          `key:"alert_p2p_allow_private_ips" desc:"Allow private IP addresses on the alert P2P network" default:"false" category:"Alert" usage:"Enable RFC1918 peers for alert P2P" type:"bool" longdesc:"### Purpose\nBy default the alert library refuses to dial or accept peers on private address ranges (10/8, 172.16/12, 192.168/16, 127/8, 100.64/10, 169.254/16) and does not advertise its own private addresses. Set to true when the alert network runs on a private network, such as a container network in a test rig.\n\n### Recommendations\n- true for regtest / private test networks\n- false (default) on mainnet"`
	P2PPeerDiscoveryInterval time.Duration `key:"alert_p2p_peer_discovery_interval" desc:"Interval between alert P2P peer discovery and sync rounds" default:"10m" category:"Alert" usage:"Alert peer discovery cadence" type:"duration" longdesc:"### Purpose\nHow often the alert service re-runs peer discovery over the DHT and syncs missing alerts from the peers it finds. The library default is 10 minutes.\n\n### Recommendations\n- Shorter values (for example 15s) on test networks to recover quickly after partitions\n- Keep the default on mainnet"`
	P2PDHTMode               string        `key:"alert_p2p_dht_mode" desc:"DHT mode for the alert P2P network" default:"client" category:"Alert" usage:"client or server" type:"string" longdesc:"### Purpose\nSelects the libp2p Kademlia DHT mode of the alert service. In **client** mode (default) the node queries the DHT but does not store records for others; in **server** mode it also serves DHT records, which lets a small private alert network form without any other DHT server.\n\n### Values\n- **client** (default)\n- **server**"`
	P2PPort                  int           `key:"ALERT_P2P_PORT" desc:"P2P port for alert service" default:"9908" category:"Alert" usage:"Port for alert P2P connections" type:"int" longdesc:"### Purpose\nSpecifies the TCP port for alert service P2P network connections, running on a **separate P2P network** from main Teranode P2P for isolation.\n\n### How It Works\n- Alert P2P operates independently from the main Teranode P2P network\n- Default port 9908 is chosen to avoid conflict with main P2P port (9906)\n- All alert network peers must be able to reach this port\n\n### Values\n- **9908** (default) - Standard alert P2P port\n- Custom port if 9908 conflicts with other services\n\n### Recommendations\n- Ensure firewall allows inbound/outbound TCP on this port\n- In containerized deployments, map to host port for external connectivity"`
}
